name = "kabuti"
compatibility_date = "2026-05-18"
main = "./worker.js"

[assets]
directory = "./"

[vars]
PANEL_URL = "https://rayoo.uk:8443/kabuti"
API_TOKEN = "j6zbQ6KF19jehkUIoWnoNAktKhINbpUq8b7gQVQ1nhM0ElH"
